<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: score.proto

namespace Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *请求参数
 *
 * Generated from protobuf message <code>grpc.UserScoreGrpcRequest</code>
 */
class UserScoreGrpcRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>int64 uid = 2;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>double change_scores = 3;</code>
     */
    private $change_scores = 0.0;
    /**
     * Generated from protobuf field <code>int32 src_id = 4;</code>
     */
    private $src_id = 0;
    /**
     * Generated from protobuf field <code>string comment = 5;</code>
     */
    private $comment = '';
    /**
     * Generated from protobuf field <code>string order_no = 6;</code>
     */
    private $order_no = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type int|string $uid
     *     @type float $change_scores
     *     @type int $src_id
     *     @type string $comment
     *     @type string $order_no
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Score::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 uid = 2;</code>
     * @return int|string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>int64 uid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt64($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double change_scores = 3;</code>
     * @return float
     */
    public function getChangeScores()
    {
        return $this->change_scores;
    }

    /**
     * Generated from protobuf field <code>double change_scores = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setChangeScores($var)
    {
        GPBUtil::checkDouble($var);
        $this->change_scores = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 src_id = 4;</code>
     * @return int
     */
    public function getSrcId()
    {
        return $this->src_id;
    }

    /**
     * Generated from protobuf field <code>int32 src_id = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSrcId($var)
    {
        GPBUtil::checkInt32($var);
        $this->src_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string comment = 5;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Generated from protobuf field <code>string comment = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_no = 6;</code>
     * @return string
     */
    public function getOrderNo()
    {
        return $this->order_no;
    }

    /**
     * Generated from protobuf field <code>string order_no = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_no = $var;

        return $this;
    }

}

