<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: score.proto

namespace GPBMetadata;

class Score
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9b020a0b73636f72652e70726f746f120467727063227b0a1455736572" .
            "53636f72654772706352657175657374120c0a0474797065180120012805" .
            "120b0a0375696418022001280312150a0d6368616e67655f73636f726573" .
            "180320012801120e0a067372635f6964180420012805120f0a07636f6d6d" .
            "656e7418052001280912100a086f726465725f6e6f18062001280922350a" .
            "0a47727063526573756c74120c0a04636f6465180120012809120b0a036d" .
            "7367180220012809120c0a0464617461180320012809324a0a0955736572" .
            "53636f7265123d0a0b75706461746553636f7265121a2e677270632e5573" .
            "657253636f726547727063526571756573741a102e677270632e47727063" .
            "526573756c742200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

