<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userservice.proto

namespace Userservice;

/**
 * Protobuf type <code>userservice.Platform</code>
 */
class Platform
{
    /**
     * Generated from protobuf enum <code>WEB = 0;</code>
     */
    const WEB = 0;
    /**
     * Generated from protobuf enum <code>APP = 1;</code>
     */
    const APP = 1;
    /**
     * Generated from protobuf enum <code>OTHER = 2;</code>
     */
    const OTHER = 2;
}

